services:
  first_service:
    build: ./my_docker_app
    container_name: first_service_container
    environment:
      SERVICE_NAME: "MY_SERVICE_1"
    entrypoint: ["python3","app1.py"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
   
  second_service:
    build: ./my_docker_app
    container_name: second_service_container
    environment:
      SERVICE_NAME: "MY_SERVICE_2"
    entrypoint: ["python3","app1.py"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    

